### ISSUE TITLE
hello,when I run vis.py,I find the erro.RuntimeError: shape mismatch: value tensor of shape [21, 256, 8, 25] cannot be broadcast to indexing result of shape [21, 256, 8, 8]

### ISSUE THREAD

**Issue by fuzheng1209** [mxin262/ESTextSpotter#12]
Traceback (most recent call last):
  File "vis.py", line 53, in <module>
    output = model(image[None].cuda())
  File "/home/lyk/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lyk/fz/ESTextSpotter/models/ests/ests.py", line 293, in forward
    hs, reference, rec_references, hs_enc, ref_enc, init_box_proposal = self.transformer(srcs, masks, input_query_bbox, poss,input_query_label,attn_mask, H, W)
  File "/home/lyk/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lyk/fz/ESTextSpotter/models/ests/deformable_transformer.py", line 396, in forward
    roi_features = self.pooler(srcs[:-2], proposal_boxes)
  File "/home/lyk/anaconda3/envs/detectron2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lyk/anaconda3/envs/detectron2/lib/python3.8/site-packages/detectron2/modeling/poolers.py", line 243, in forward
    output.index_put_((inds,), pooler(x[level], pooler_fmt_boxes_level))
RuntimeError: shape mismatch: value tensor of shape [21, 256, 8, 25] cannot be broadcast to indexing result of shape [21, 256, 8, 8]

**Comment by mxin262** [comment]
Use the detectron2 in this repository.
